#==========Version
version: '3.6'

#==========Service
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose:
      - "3306"

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    expose:
      - "9000"

#==========Volume
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/alee/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/alee/data/wordpress

#==========Network
networks:
  inception:
    name: inception-network
    driver: bridge
